env:
 - CABALVER=1.20 GHCVER=7.4.2
 - CABALVER=1.20 GHCVER=7.6.3
 - CABALVER=1.20 GHCVER=7.8.4
 - CABALVER=1.20 GHCVER=7.10.1
 - CABALVER=1.20 GHCVER=7.10.2

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal install cabal-src cabal-meta alex happy

script:
 - cabal-meta install --only-dependencies --run-tests --enable-benchmarks --force-reinstalls
